# Generated by Django 2.1.7 on 2021-04-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
