# Generated by Django 2.1.7 on 2021-04-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie', '0002_blogs_averagerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='averageRating',
        ),
    ]
