# Generated by Django 2.1.7 on 2021-04-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie', '0003_remove_blogs_averagerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_date',
            new_name='pub_date',
        ),
    ]
